### ISSUE TITLE
CityEngine SDK do not support shape or gdb as input? Why?

### ISSUE THREAD

**Issue by chaogis** [Esri/cityengine-sdk#36]
CityEngine support shapefile and gdb as input shape. However, i check the build-in encoders(https://esri.github.io/cityengine-sdk/html/esri_prt_codecs.html), as the following pictures:
![build-in encoders](https://user-images.githubusercontent.com/32628057/103335562-3b07d280-4ab0-11eb-9298-0b9131389351.png)

There is no shapefile and gdb, i want to ask why? Is cityengine sdk not support, or i have misunderstood?

I hope hear from you soon, thank you!

**Comment by mistafunk** [comment]
Hi & happy new year!

The "Esri Shapebuffer Encoder" produces the raw multipatch/multipart/... byte arrays. Writing the actual container files to disk (e.g. Shapefile or FileGDB) is not part of the CityEngine SDK (PRT) and left to the host application.

There are separate C/C++ SDKs/APIs available to write the container files:
* To write FileGDBs you can use the separate FileGDB API, also available on github: https://github.com/Esri/file-geodatabase-api/tree/master/FileGDB_API_1.5.1
* To write Shapefiles you can use http://shapelib.maptools.org

Background: if the format allows, we usually abstract direct disk I/O away from our encoders. This makes them more versatile, e.g. storing the encoded bytes into a custom database instead of plain files.

**Comment by chaogis** [comment]
> Hi & happy new year!
> 
> The "Esri Shapebuffer Encoder" produces the raw multipatch/multipart/... byte arrays. Writing the actual container files to disk (e.g. Shapefile or FileGDB) is not part of the CityEngine SDK (PRT) and left to the host application.
> 
> There are separate C/C++ SDKs/APIs available to write the container files:
> 
> * To write FileGDBs you can use the separate FileGDB API, also available on github: https://github.com/Esri/file-geodatabase-api/tree/master/FileGDB_API_1.5.1
> * To write Shapefiles you can use http://shapelib.maptools.org
> 
> Background: if the format allows, we usually abstract direct disk I/O away from our encoders. This makes them more versatile, e.g. storing the encoded bytes into a custom database instead of plain files.

OK，glad to hear from you. Thanks for you advice, i will try it. You can close this issue now.
